NYCPlanning/labs-factfinder-api

utils/carto.js
=> switch to new carto endpoint

app.js, package-lock.json, package.json
https://expressjs.com/en/advanced/best-practice-performance.html#use-gzip-compression
Closes #2
=> Add gzip compression

query-helpers/decennial.js, query-helpers/profile-single.js, query-helpers/profile.js
This PR changes and cleans up the SQL queries. It carries changes made in regular profile SQL calc into the special single-geog calc.
- New Feature
- API change
Closes NYCPlanning/labs-nyc-factfinder#450 
Closes NYCPlanning/labs-nyc-factfinder#409
=> Fix single geogs

metadata/top-bottom-codings.js, routes/profile.js, utils/delegate-aggregator.js, utils/interpolate.js, utils/median-of-ranges.js, utils/top-bottom-code-estimate.js
This PR addresses NYCPlanning/labs-nyc-factfinder#157
Adds logic for top-bottom coding for the interpolation step.
=> Top bottom coding

package-lock.json, query-helpers/profile-single.js, query-helpers/profile.js, table-config/decennial/housing-occupancy.js, table-config/decennial/housing-tenure.js, table-config/decennial/population-density.js, table-config/decennial/relationship-to-head-of-household--householder.js, table-config/decennial/sex-and-age.js, table-config/demographic/sex-and-age.js, table-config/housing/housing-occupancy.js, table-config/housing/housing-tenure.js, table-config/housing/rooms.js, table-config/social/household-type.js
This PR coalesces change_m input MOEs to zero if they're null.
Closes NYCPlanning/labs-nyc-factfinder#426
=> 426 treat est zero moe as 0

table-config/decennial/housing-occupancy.js, table-config/decennial/housing-tenure.js, table-config/decennial/population-density.js, table-config/decennial/relationship-to-head-of-household--householder.js, table-config/decennial/sex-and-age.js, table-config/demographic/sex-and-age.js, table-config/housing/housing-occupancy.js, table-config/housing/housing-tenure.js, table-config/housing/rooms.js, table-config/social/household-type.js
This PR adds table configurations to hide percent change for select variables
Closes #448
=> Add configurations for hiding pct chng

query-helpers/profile-single.js, routes/profile.js, table-config/economic/income-and-benefits.js, utils/carto.js
Closes NYCPlanning/labs-nyc-factfinder#511 and Closes NYCPlanning/labs-nyc-factfinder#512
This PR {summarize the PR}
- New Feature
- API change
Closes #{issue number(s)}
=> Fix divide by zero

query-helpers/profile-single.js, query-helpers/profile.js
…ation
This PR {summarize the PR}
- New Feature
- API change
Closes #{issue number(s)}
=> Add coalesce to difference pctg pt and percent change

table-config/decennial/relationship-to-head-of-household--householder.js, table-config/decennial/sex-and-age.js
This PR changes configuration for variable names related to `Under 18 years`
=> Update data for Census Under 18

query-helpers/profile-single.js, query-helpers/profile.js
=> Add coalesce to significance to treat null MOE as 0

routes/profile.js
Finishes adding logic for significance of special variables (number difference)
Closes #525
=> Add logic for special variable difference significance

query-helpers/profile-single.js, query-helpers/profile.js, test-output/1-demographic-0.yaml
change_percent_m null only if previous_sum zero. Also, coalesce non zero previous sums into 0s even if there is a null
Some output is changing
Closes #29
=> change_percent_m null only if previous_sum zero

query-helpers/profile-single.js, query-helpers/profile.js, routes/profile.js, test-output/1-demographic-0.yaml
Update to difference and change significance formulas to calculate a CV for each estimate/MOE pair to determine reliability.
I think I updated each instance, but please check that I didn't miss any other significance calculations in the code.
=> Update to difference/change significance formulas

utils/inflate.js
=> 653: update inflation value for 2017

table-config/economic/commute-to-work.js, table-config/economic/income-and-benefits.js, table-config/housing/housing-tenure.js, table-config/social/household-type.js
Small adjustments to the mean formulas which came out of meeting with Joel. The mean MOE calcs were off, this was due to an incorrectly wrapped parentheses.
=> Fix mean moe

query-helpers/decennial.js, query-helpers/profile.js
This PR {summarize the PR}
- New Feature
- API change
Closes #{issue number(s)}
=> Increase selectivity in queries to avoid ambiguous values

routes/profile.js, special-calculations/data/top-bottom-codings.js
These values are published by the Census Bureau.
Top and Bottom Codings refer to special handling for certain variables published by the ACS. They are the lower and upper range bounds for an aggregated estimate that exceeds a certain reliability threshold. For example, if a the estimated aggregate median income is $260,750, and the upper bounds of the top-coding is $250,000, it will display "$250,000+".
This PR updates these values to reflect inflation updates.
Addresses #82
=> Updates static top and bottom coding values

models/selection.js, routes/search.js, yarn.lock
This PR {summarize the PR}
Removes CDTA and Borough from appearing in search results.
=> Removing cdta and borough from search results.

utils/data-processor.js
This PR will adjust inflation for single geometry/geography variables (in addition to custom aggregation geometry/geographies)
- New Feature
- API change
Closes #4095
=> 4095  adjust inflation for single geometry/geography

README.md
Making FactFinder capitalization consistent with what is used throughout the product.
=> Update copy in the readme

routes/profile.js, utils/change.js, utils/difference.js
sample response
```json
[
{
"id":"amFtYWljYQ==",
"variable":"jamaica",
"variablename":"Jamaica",
"base":"Fb2",
"category":"place_of_birth",
"profile":"social",
"current":{
"sum":4794,
"m":0,
"cv":null,
"percent":0.072,
"percent_m":0,
"is_reliable":false
},
"previous":{
"sum":6211,
"m":0,
"cv":null,
"percent":0.101,
"percent_m":0,
"is_reliable":false
},
"compare":{
"sum":167467,
"m":3817,
"cv":1.4,
"percent":0.054,
"percent_m":0.001,
"is_reliable":true
},
"preivousCompare":{
"sum":168327,
"m":4088,
"cv":1.5,
"percent":0.057,
"percent_m":0.001,
"is_reliable":true
},
"difference":{
"sum":-162673,
"m":3817,
"significant":true,
"percent":1.799999999999999,
"percent_m":0.1,
"percent_significant":true
},
"previousDifference":{
"sum":-162116,
"m":4088,
"significant":true, …
```
=> 4222 Streamline Join process and Row data construction

routes/profile.js
Renames to `/profile` endpoint's `comparison` parameter to `compareTo`
Pairs with https://github.com/NYCPlanning/labs-factfinder/pull/877
- Fixes [AB#3892](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3892)
=> 38920 Change compare param to compareTo

routes/survey.js, utils/data-processor.js, utils/formula.js, utils/interpolate.js
This PR cleans up references to `profile` in favor of `survey` to keep things consistent
- Related AB#4492
- Related [AB#4806](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4806)
=> Removing profile references

utils/change.js, utils/difference.js
See @SPTKL 's comments below for summary 
- Fixes [AB#4926](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4926)
=> 4926 Fix faulty shouldNullify logic 

migrations/selection.sql
Removed id, made hash primary key in migration script.
- Closes [AB#4293](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4293)
=> 4293 Remove id from selection table

utils/difference.js
difference significant calculation was using `m` instead of `difference.m` for significant calculation, 
which leads to everything insignificant 
- Fixes [AB#5033](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/5033)
=> 5033 - Difference significant calculation fix (using wrong input variable)

utils/difference.js
This PR fixes a missed variable rename
- Fixes [AB#4229](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4229)
=> Missed a variable renaming

migrations/support_geoids.sql, utils/difference.js
This updates the support geoid migration to fix the label for city and borough geos
- Fixes [AB#5125](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5125)
=> Fixing city and borough label in migrations

migrations/decennial_metadata.sql, migrations/selection.sql, query-helpers/decennial.js
This PR renames the "relation" column in the decennial table to "base" to be consistent with the ACS table
- Fixes [AB#4905](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4905)
=> 4905 relation base refactor

utils/carto.js
Fixes [AB#7557](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/7557)
=> 7557 Set Carto account via environment

search-helpers/geosearch.js
Fixes [AB#9388](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/9388)
Tested and working locally.
=> Consume Geosearch v2

app.js
Fixing a production issue with the CORS policy introduced in PR #216
=> fix production CORS url

routes/selection.js, routes/summary.js
- Add post request to accept the same from PRR
- tweaked error logging to be more descriptive
- Fixes [[AB#12726](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/12726)(https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/12726))
- Related [PR#1079](https://github.com/NYCPlanning/labs-factfinder/pull/1079)
=> 12726 add post request to handle selection summary requests from PFF

README.md, package.json
- Remove volta object
- Update readme node reference to point to .nvmrc
- Supports [AB#12780](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/12780)
=> 12780: remove volta object and readme listing of specific version

.github/workflows/ci.yml, migrations/cli.sh, migrations/etl.sh, routes/selection.js
Fix error in which invalid selections cause an error within the API
- Fixes [AB#14700](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/14700)
=> Fix for AB#14700, invalid selection type will cause server error

.github/workflows/ci.yml, migrations/cli.sh, migrations/etl.sh, routes/selection.js
- Update the CI to build with node 18
- Point to archive folder for source data
- Safely handle invalid geotype requests
- Fixes [AB#14700](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/14700)
=> Develop to Staging for AB#14700

.github/workflows/ci.yml, migrations/cli.sh, migrations/etl.sh, routes/selection.js
- Update the CI to build with node 18
- Point to archive folder for source data
- Safely handle invalid geotype requests
- Fixes [AB#14700](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/14700)
=> Staging to Master for AB#14700

special-calculations/data/top-bottom-codings.js
=> Update top and bottom codings

special-calculations/data/constants.js
=> Update inflation and current year

special-calculations/housing.js
Closes https://github.com/NYCPlanning/labs-factfinder-api/issues/326
=> Update mean gross rent variable to show percents change

special-calculations/housing.js
This PR merges the first round of feedback from 2025 back end data update to staging
=> Merge feedback iteration 1 from 2025 back end data update to staging
