package-lock.json
package.json
routes/profile.js

This PR adds a package called `cwait` that lets you wrap Promises and queue them. In this case, we limit concurrent Promises (which are fetches) by 2 so as not to overload Carto.

Wrap promises and limit to 2 concurrent requests

---

.env-example
README.md
package-lock.json
routes/search.js
search-helpers/geosearch.js

This PR removes all references to [Mapzen Search](https://mapzen.com/search/), and swaps them for [NYC GeoSearch](https://geosearch.planninglabs.nyc/). 
Closes #15.

Switch to NYC GeoSearch

---

package.json
query-helpers/profile-single.js
query-helpers/profile.js
routes/profile.js
test-output/1-demographic-0.yaml
test/profile.test.js

This PR closes NYCPlanning/labs-nyc-factfinder#539 by fixing the missing percentage point differences

539 pct pnt chng language

---

query-helpers/profile-single.js
test/profile.test.js

This PR changes the way percent pt significance is calculated.
- New Feature
- API change
Closes NYCPlanning/labs-nyc-factfinder#548

Approach pct pt differently

---

metadata/top-bottom-codings.js

Edit top and bottom coding values for aggregated geogs for ntas based off of: 
Latest:
single-geography estimates - use "all", except when NTA (then use "nta")
**multi-geography aggregates - use "nta"**
Earlier:
single-geography estimates - use "all", except when NTA and PUMA (then use "nta")
**multi-geography aggregates - use "nta"**
closes #657 
https://github.com/NYCPlanning/labs-factfinder/issues/657

657: Edit top and bottom coding values

---

query-helpers/profile-single.js
query-helpers/profile.js
routes/profile.js

References issue #57 . 
In PR #39, calculations were changed from determining SIGNIFICANCE to determining RELIABILITY, but variable names were not updated to reflect this change. Variable names will be updated during a broader refactor of PFF. As of now, comments were added to note this change.

Create comments--calculation changes from signficance to reliability

---

search-helpers/block.js
search-helpers/neighborhood-tabulation-area.js
search-helpers/tract.js
selection-helpers/summary-levels.js

This PR updates Carto queries to query from aliased views of the latest dataset version. This reduces data maintenance overhead (now we only need to redefine the view when we get a new data version instead of find/replacing the table name throughout the code base) and makes this app match data view references used in all our other apps.
Related to https://github.com/NYCPlanning/labs-layers-api/pull/124

use-aliased-data

---

routes/profile.js
utils/data-processor.js
utils/interpolate.js

Many errors were being swallowed in the logs and returning improper data. This change explicitly throws an error when data returned from the database is incorrect. This helps prevent the app from silently returning totally wrong data.
This change also adds some helpful logging to debug quicker.

Throw error (rather than silence log); improve error msg

---

migrations/1580836697651_add-sort-order-to-acs-metadata.js

This column is not used in the app, however, EDM and I added it while trying to debug some issues. We found that sorting was not the source of the issue.
Instead of reverting the schema change, this commit keeps the migration. It’s necessary still because any schema changes EDM-side will cause the foreign data wrappers to fail, preventing future refreshes.
During a later refactor, it should be used as an identifier to assist with explicit sorting.

Adds a migration for a change to the metadata schema EDM-side

---

.circleci/config.yml

This removes the deploy step from the Cricle CI configuration. Because the app is deployed through Heroku, it any pushes to develop automatically trigger a deployment.

Remove deploy step

---

utils/change.js
utils/difference.js

Previously, decennial change calculations weren’t being made because the code did not take into account that change in sum calculations may be performed on decennial with the need for reliability statistics.
Now, the logic considers the type of profile (decennial).

Expand logic for handling change calculations in decennial profiles

---

utils/change.js
utils/difference.js

Previously, decennial change/difference calculations weren’t being made because the code did not take into account that difference in sum calculations may still be performed on decennial profiles withOUT the need for reliability statistics. this is because decennial census data is not sampled and doesn’t include error.
Now, the logic considers the type of profile (decennial) and allows for calculating the change/difference in sum for decennial profiles.
This commit also refactors some of the code is it’s a little easier to follow and exposes the complexity more clearly...

736 decennial change over time

---

utils/formulas.js

This multiplies the sum ratio result by 100 so that it is displayed as a whole number for presentation purposes.
Closes https://github.com/NYCPlanning/labs-factfinder/issues/742

Multiply the sum_ratio result by 100

---

README.md
routes/profile.js
utils/change.js

Certain decennial change calculations were failing because they were new categories that could not be compared to previous releases.
This change wraps the calculations code in a try/catch to prevent failure. Note that this should be changed later to more explicitly validate decennial inputs, and skip accordingly.

Wrap calculations in try/catch to skip invalid inputs

---

README.md
package-lock.json
query-helpers/profile.js
routes/profile.js
routes/selection.js
selection-helpers/summary-levels.js
utils/geotype-from-id-prefix.js

Reworks the Profile and Selection GET routes to accept both Selection IDs and Geoid. The routes also require passing in a geotype code. Please see changes to  README.md for an overview. 
Essentially, if the routes detect a selection ID, they will query the selection table for geometry. If they detect a geoid, which represent a single well known geography, they will query Carto directly for the geometry.
Fixes [AB#4212](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4212) [AB#3926](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/3926)
Works with https://github.com/NYCPlanning/labs-factfinder/pull/862

3926 enable higher level geo codes

---

routes/profile.js
utils/difference.js

This PR modifies the API so that the Profile endpoint will deliver comparison area and difference data when the user selects a "previous year" source  (e.g. 2010 for ACS). 
In the screenshot below, it is the data for the middle "New York City" (comparison) and right hand side "Difference" columns.
Previously, only the current year (2020) source delivered comparison area and comparison data. The Change over Time source delivered only "change" data, which is the diff between previous and current year "selected area" data. 
In the table below, it is the middle row, last two columns of data that was missing from the payload. 
Frontend PR https://github.com/NYCPlanning/labs-factfinder/pull/869 subsequently will display these newly added variables. 
Fixes …

4401 Include previous_comparison and previous_difference in Profile payload model 

---

README.md
routes/profile.js
routes/selection.js

Changes Selection and Profile endpoints to have :geotype and :geoid dynamic segments, replacing the previous Factfinder ID. 
See updated README for new API. 
Pairs with https://github.com/NYCPlanning/labs-factfinder/pull/881
Depends on/merge after https://github.com/NYCPlanning/labs-factfinder-api/pull/130
- Fixes [AB#4281](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4281)

4281 Dynamic segments for geotype and geoid

---

selection-helpers/summary-levels.js

Fixes error caused by attempting to take substring of an integer by casting it as a string.
No ticket created
Resolves the following error:
'{"error":["function pg_catalog.substring(integer, integer, integer) does not exist"],"hint":"No function matches the given name and argument types. You might need to add explicit type casts."}',

District SQL Query Fix

---

query-helpers/acs.js
query-helpers/decennial.js

The new data tables lowercases all variable names and  base names, but the old tables did not. Thus percentages wouldn't show up. This is just a extra safeguard  to make sure the variable and base comparison works properly. 
- Fixes [AB#4220](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/4220)

4220 Lowercase base and variable to make sure percentages show up

---

utils/data-processor.js

The recalculateCV function was running for single geoms (selections) when it shouldn't be. This was causing many of "failed to update sepcial vars" errors. This PR makes sure that function only runs when there are multiple geoms (a selection)
```
((GET("m") / "1.645") / GET("sum")) * 100
Failed to update special vars for avgfmsz: Error: #VALUE!: cv
at executeWithData (.../labs-factfinder-api/utils/formula.js:67:11)
at DataProcessor.recalculateCV (.../labs-factfinder-api/utils/data-processor.js:138:32)
at DataProcessor.recalculateSpecialVariables (.../labs-factfinder-api/utils/data-processor.js:75:14)
at .../labs-factfinder-api/utils/data-processor.js:50:16
at Array.forEach (<anonymous>)
at DataProcessor.process (.../labs-factfinder-api/utils/data-processor.js:44:15)
at getSurveyData …
```

4725 Fix error yielded from recalculateCV

---

special-calculations/decennial.js

based on Erica's commend on Teams: 
> for decennial `avghhsz`, using existing variables it would be `popinhh/ochu_1`.
The error occurred because `hh1` is not part of the PL release. Confirmed with Erica that we will use `ochu_1` instead
This should resolve this following error:

Fixing special calculation error for decennial avghhsz: change hh1 to ochu_1

---

utils/change.js

For the change calculation, `previous_m` was mapped to `previous_percent_m` by mistake, which made the `percentage_point_m` look really large for a lot of the variables. 
e.g. 
- Fixes [AB#5041](https://dev.azure.com/NYCPlanning/ITD/_workitems/edit/5041)

5041 - Fixing Change percentage point MOE calculation input for previous_percent_m

---

special-calculations/data/constants.js

We need to update the inflation constant to the new value for 2020 data. The new inflation value is 1.1898.
This should be as simple as updating the "INFLATION_FACTOR" constant in the backend repo in `/special-calculations/data/constants.js` 
This only effects data that represent a monetary value and numbers are only inflated for 2006-2010 data, so you need to make sure you select the ACS 2006-2010 data from the data source dropdown to test these changes:
Image. To test this, you may want to compare numbers for monetary data points as they show up in the app to the values in the database. Here are the variable IDs that get inflated (Note they are all lowercase in the front end app code and the database. Look at the column variable in the "2010" table under the "acs" schema in the db to …

9773 Update Inflation Constant to 2020 Value

---

search-helpers/geosearch.js

Reverts NYCPlanning/labs-factfinder-api#190
This is to release new PFF data before we complete QA of geosearch v2 in pff.

Temporarily revert "Consume Geosearch v2"

---

app.js
routes/summary.js

Adds an API route used to provide summary totals to the map selection box.
- Along with a corresponding [pr in labs-factfinder](https://github.com/NYCPlanning/labs-factfinder/pull/1025), completes [AB#5537](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/5537)

5537 Add the population and housing facts to the map selection box

---

bin/www
query-helpers/acs.js
utils/data-processor.js

This PR attempts to address AB[#10016](https://dev.azure.com/NYCPlanning/ITD/_sprints/taskboard/Open%20Source%20Engineering/ITD/2022/Q3/Sprint%20R?workitem=10016). The main issue is a line of SQL in [acs.js](https://github.com/NYCPlanning/labs-factfinder-api/blob/c2690b69f0b0c65c732d28dbd10ae2000db5d2dd/query-helpers/acs.js#L112) which coalesces any null MOE values to 0. However, without this line some other MOEs are not calculated – particularly those in the difference table rows.
~~A similar issue with null values was occurring with the coefficient of correlation. When we recalculate the reliability of a given row, we execute the isReliable formula with FormulaParser. The [formula](https://github.com/NYCPlanning/labs-factfinder-api/blob/c2690b69f0b0c65c732d28dbd10ae2000db5d2dd/utils/form …

10016 - Prevent null value MOEs from being coalesced to 0

---

utils/data-processor.js

When recalculating the reliability of a given row, we execute the isReliable formula with FormulaParser. The [formula](https://github.com/NYCPlanning/labs-factfinder-api/blob/c2690b69f0b0c65c732d28dbd10ae2000db5d2dd/utils/formulas.js#L36) checks if the cv is under 20 and if it is, returns true. However, if that cv is null (as in the case of [AB#10016](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/10016)), this will incorrectly return true. So I added this simple check to see if there is a cv before recalculating.

Check that row cv is not null before recalculating reliability

---

app.js

Currently we cannot reach https://factfinder-api-develop.herokuapp.com from local environments due to the existing CORS policy defined in `app.js`. This PR adds `http://localhost:4200` to that policy so that we can reach it from the default port defined when running `npm run start` over in the PFF front end repo.

Add localhost with default FE port to CORS policy

---

special-calculations/data/top-bottom-codings.js

*UPDATED THRESHOLDS FOR TOP/BOTTOM VARIABLES*
2017-2021
Housing –
Top- and bottom-coding changes:
MdVl:
Top: no changes
Bottom: median calculation: 10,000, shown as: 10,000-
2006-2010
Economic – 
Top- and bottom-coding changes:
MdHHInc:
Top: median calculation: 200,000, inflated/shown as: 250,000+
Bottom: median calculation: 9,999, inflated/shown as: 12,500-
MdFamInc:
Top: median calculation: 200,000, inflated/shown as: 250,000+
Bottom: median calculation: 9,999, inflated/shown as: 12,500-
MdNFInc:
Top: median calculation: 200,000, inflated/shown as: 250,000+
Bottom: median calculation: 9,999, inflated/shown as: 12,500-
MdEWrk:
Top: median calculation: 100,000, inflated/shown as: 125,000+
Bottom: median calculation: 2,499, inflated/shown as: 3,100-
MdEMFTWrk:
Top: median calculation: …

12685 updated thresholds for top and bottom variables

---

migrations/metadata.sh

- Sibling to https://github.com/NYCPlanning/labs-layers-api/pull/304
- Update migrations to target main branch
- Supports task [AB#12720](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/12720)
- Supports user story [AB#12652](https://dev.azure.com/NYCPlanning/cc280b0d-40a0-4689-b852-2e6247f1af50/_workitems/edit/12652)
`dev` database branch was replaced with `main`. Migrations scripts have been updated accordingly.
These changes do not effect live environments. They update a manual migration job.

task/12720: update migrations to target main branch

---

README.md

Alter the readme to give primacy to setting up with the local database. 
The local db should have primacy because:
1. It is the only option available to the broader community
2. It fits the environment state established in the previous step. Specifically, it uses the values from the `sample.env` file described in step 4 (the previous step)

give primacy to the local db setup instructions

---

app.js

This PR updates the CORS policy to including planninglabs.nyc domains for staging and develop.

Add planninglabs.nyc domains to CORS

---

routes/search.js
search-helpers/cdta.js

Fixes an issue where when searching for a CDTA, the search and map does not yield a result.
- Along with [Factfinder #1156](https://github.com/NYCPlanning/labs-factfinder/pull/1156) completes [Factfinder API Issue #289](https://github.com/NYCPlanning/labs-factfinder-api/issues/289)

289 Search results now include CDTAs

---

utils/data-processor.js

top and bottom coded values should be grey. This fix keeps another [bug fix](https://github.com/NYCPlanning/labs-factfinder-api/pull/204) intact while properly set `isCoded` which in turn sets `isReliable` to false when value is top or bottom coded.
- Closes #303

issue 303 get coded rows to set isReliable to false when top/bottom coded
